export const NEIGHBORHOODS: Record<string, string[]> = {
  'Albuquerque': [
    'Barelas',
    'Downtown',
    'Huning Highland',
    'Los Ranchos',
    'Nob Hill',
    'North Valley',
    'Old Town',
    'Sandia Heights',
    'South Valley',
    'Uptown',
  ],
  'Atlanta': [
    'Buckhead',
    'Cabbagetown',
    'Decatur',
    'Downtown',
    'East Atlanta',
    'Grant Park',
    'Inman Park',
    'Little Five Points',
    'Midtown',
    'Old Fourth Ward',
    'Virginia-Highland',
    'West End',
  ],
  'Austin': [
    'Barton Hills',
    'Clarksville',
    'Downtown',
    'East Austin',
    'Hyde Park',
    'Mueller',
    'North Loop',
    'South Congress',
    'South Lamar',
    'Travis Heights',
    'Westlake Hills',
    'Zilker',
  ],
  'Baltimore': [
    'Canton',
    'Charles Village',
    'Federal Hill',
    'Fells Point',
    'Hampden',
    'Harbor East',
    'Inner Harbor',
    'Locust Point',
    'Mount Vernon',
    'Patterson Park',
    'Remington',
    'Roland Park',
  ],
  'Boston': [
    'Allston',
    'Back Bay',
    'Beacon Hill',
    'Charlestown',
    'Dorchester',
    'Fenway',
    'Jamaica Plain',
    'North End',
    'Roxbury',
    'South Boston',
    'South End',
    'West Roxbury',
  ],
  'Charlotte': [
    'Ballantyne',
    'Dilworth',
    'Elizabeth',
    'Myers Park',
    'NoDa',
    'Plaza Midwood',
    'South End',
    'South Park',
    'Steele Creek',
    'University City',
    'Uptown',
  ],
  'Chicago': [
    'Bucktown',
    'Gold Coast',
    'Hyde Park',
    'Lakeview',
    'Lincoln Park',
    'Logan Square',
    'Loop',
    'Old Town',
    'Pilsen',
    'River North',
    'South Loop',
    'West Loop',
    'Wicker Park',
    'Wrigleyville',
  ],
  'Cleveland': [
    'Detroit Shoreway',
    'Downtown',
    'Edgewater',
    'Little Italy',
    'Ohio City',
    'Old Brooklyn',
    'Slavic Village',
    'Tremont',
    'University Circle',
  ],
  'Columbus': [
    'Clintonville',
    'Downtown',
    'German Village',
    'Grandview Heights',
    'Italian Village',
    'King-Lincoln',
    'Short North',
    'University District',
    'Upper Arlington',
    'Victorian Village',
  ],
  'Dallas': [
    'Bishop Arts',
    'Deep Ellum',
    'Design District',
    'Downtown',
    'Greenville Avenue',
    'Highland Park',
    'Knox-Henderson',
    'Lakewood',
    'Oak Cliff',
    'Oak Lawn',
    'Preston Hollow',
    'Uptown',
  ],
  'Denver': [
    'Baker',
    'Capitol Hill',
    'Cherry Creek',
    'City Park',
    'Downtown',
    'Five Points',
    'Highlands',
    'LoDo',
    'Park Hill',
    'RiNo',
    'Washington Park',
  ],
  'Detroit': [
    'Brush Park',
    'Corktown',
    'Downtown',
    'Eastern Market',
    'Indian Village',
    'Mexicantown',
    'Midtown',
    'New Center',
    'Palmer Park',
    'Rosedale Park',
  ],
  'Fort Worth': [
    'Arlington Heights',
    'Camp Bowie',
    'Cultural District',
    'Downtown',
    'Fairmount',
    'Magnolia Avenue',
    'Near Southside',
    'Northside',
    'Southside',
    'Stockyards',
    'TCU',
  ],
  'Honolulu': [
    'Ala Moana',
    'Diamond Head',
    'Downtown',
    'Hawaii Kai',
    'Kailua',
    'Kaimuki',
    'Kakaako',
    'Kaneohe',
    'Manoa',
    'Waikiki',
  ],
  'Houston': [
    'Downtown',
    'EaDo',
    'Galleria',
    'Greater Heights',
    'Midtown',
    'Montrose',
    'Museum District',
    'Rice Village',
    'River Oaks',
    'The Heights',
    'Third Ward',
    'Upper Kirby',
    'West University',
  ],
  'Indianapolis': [
    'Broad Ripple',
    'Downtown',
    'Fletcher Place',
    'Fountain Square',
    'Irvington',
    'Mass Ave',
    'Meridian Hills',
    'Meridian-Kessler',
    'SoBro',
    'Speedway',
  ],
  'Jacksonville': [
    'Avondale',
    'Beaches',
    'Downtown',
    'Five Points',
    'Mandarin',
    'Murray Hill',
    'Ortega',
    'Riverside',
    'San Marco',
    'Springfield',
  ],
  'Las Vegas': [
    'Arts District',
    'Centennial Hills',
    'Chinatown',
    'Downtown',
    'Green Valley',
    'Henderson',
    'Paradise',
    'Spring Valley',
    'Summerlin',
    'The Strip',
  ],
  'Los Angeles': [
    'Arts District',
    'Beverly Hills',
    'Brentwood',
    'Culver City',
    'Downtown',
    'Echo Park',
    'Highland Park',
    'Hollywood',
    'Koreatown',
    'Los Feliz',
    'Santa Monica',
    'Silver Lake',
    'Venice',
    'West Hollywood',
    'Westwood',
  ],
  'Louisville': [
    'Butchertown',
    'Clifton',
    'Crescent Hill',
    'Downtown',
    'Germantown',
    'Highlands',
    'NuLu',
    'Old Louisville',
    'Schnitzelburg',
    'St. Matthews',
  ],
  'Memphis': [
    'Central Gardens',
    'Cooper-Young',
    'Crosstown',
    'Downtown',
    'East Memphis',
    'Germantown',
    'Harbor Town',
    'Midtown',
    'Overton Park',
    'South Main',
  ],
  'Miami': [
    'Brickell',
    'Coconut Grove',
    'Coral Gables',
    'Design District',
    'Downtown',
    'Key Biscayne',
    'Little Haiti',
    'Little Havana',
    'Miami Beach',
    'Midtown',
    'South Beach',
    'Wynwood',
  ],
  'Milwaukee': [
    'Bay View',
    'Brady Street',
    'Downtown',
    'East Side',
    'Historic Third Ward',
    'Juneau Town',
    'Riverwest',
    'Shorewood',
    'Walker\'s Point',
    'Wauwatosa',
  ],
  'Minneapolis': [
    'Cedar-Riverside',
    'Downtown',
    'Eat Street',
    'Kenwood',
    'Longfellow',
    'Loring Park',
    'Lowry Hill',
    'North Loop',
    'Northeast',
    'Seward',
    'Uptown',
    'Whittier',
  ],
  'Nashville': [
    '12 South',
    'Downtown',
    'East Nashville',
    'Germantown',
    'Green Hills',
    'Gulch',
    'Marathon Village',
    'Midtown',
    'Music Row',
    'Sylvan Park',
    'The Nations',
    'Wedgewood-Houston',
  ],
  'New Orleans': [
    'Bywater',
    'CBD',
    'French Quarter',
    'Garden District',
    'Gentilly',
    'Irish Channel',
    'Lakeview',
    'Lower Garden District',
    'Marigny',
    'Mid-City',
    'Treme',
    'Uptown',
    'Warehouse District',
  ],
  'New York': [
    'Astoria',
    'Bedford-Stuyvesant',
    'Brooklyn Heights',
    'Bushwick',
    'Chelsea',
    'Chinatown',
    'Crown Heights',
    'DUMBO',
    'East Village',
    'Financial District',
    'Flushing',
    'Fort Greene',
    'Greenpoint',
    'Greenwich Village',
    'Harlem',
    'Hell\'s Kitchen',
    'Long Island City',
    'Lower East Side',
    'Midtown',
    'Park Slope',
    'SoHo',
    'TriBeCa',
    'Upper East Side',
    'Upper West Side',
    'Williamsburg',
  ],
  'Orlando': [
    'Audubon Park',
    'Baldwin Park',
    'College Park',
    'Downtown',
    'Lake Nona',
    'Milk District',
    'Mills 50',
    'Parramore',
    'Thornton Park',
    'Winter Park',
  ],
  'Philadelphia': [
    'Center City',
    'Chestnut Hill',
    'East Passyunk',
    'Fairmount',
    'Fishtown',
    'Germantown',
    'Manayunk',
    'Northern Liberties',
    'Old City',
    'Rittenhouse Square',
    'Society Hill',
    'South Philadelphia',
    'University City',
  ],
  'Phoenix': [
    'Ahwatukee',
    'Arcadia',
    'Biltmore',
    'Camelback East',
    'Central City',
    'Desert Ridge',
    'Downtown',
    'Encanto',
    'Maryvale',
    'Paradise Valley',
    'South Mountain',
  ],
  'Pittsburgh': [
    'Bloomfield',
    'Downtown',
    'East Liberty',
    'Highland Park',
    'Lawrenceville',
    'Mount Washington',
    'North Side',
    'Oakland',
    'Shadyside',
    'South Side',
    'Squirrel Hill',
    'Strip District',
  ],
  'Portland': [
    'Alberta Arts',
    'Buckman',
    'Division',
    'Downtown',
    'Hawthorne',
    'Hollywood',
    'Irvington',
    'Kenton',
    'Mississippi',
    'Pearl District',
    'Sellwood',
    'St. Johns',
  ],
  'Raleigh': [
    'Cameron Village',
    'Downtown',
    'Five Points',
    'Glenwood South',
    'Hayes Barton',
    'Hillsborough Street',
    'Midtown',
    'Moore Square',
    'North Hills',
    'Oakwood',
  ],
  'Sacramento': [
    'Curtis Park',
    'Downtown',
    'East Sacramento',
    'Elk Grove',
    'Land Park',
    'Lavender Heights',
    'Midtown',
    'Natomas',
    'Oak Park',
    'R Street',
  ],
  'Salt Lake City': [
    'Avenues',
    'Capitol Hill',
    'Central City',
    'Downtown',
    'East Bench',
    'Granary District',
    'Liberty Wells',
    'Marmalade',
    'Rose Park',
    'Sugar House',
  ],
  'San Antonio': [
    'Alamo Heights',
    'Dignowity Hill',
    'Downtown',
    'Government Hill',
    'King William',
    'Lavaca',
    'Monte Vista',
    'Olmos Park',
    'Pearl District',
    'Southtown',
    'Stone Oak',
    'Tobin Hill',
  ],
  'San Diego': [
    'Bankers Hill',
    'Downtown',
    'East Village',
    'Gaslamp Quarter',
    'Hillcrest',
    'La Jolla',
    'Little Italy',
    'Mission Beach',
    'Mission Hills',
    'North Park',
    'Ocean Beach',
    'Old Town',
    'Pacific Beach',
    'Point Loma',
  ],
  'San Francisco': [
    'Castro',
    'Chinatown',
    'Dogpatch',
    'Financial District',
    'Haight-Ashbury',
    'Hayes Valley',
    'Marina',
    'Mission',
    'Nob Hill',
    'Noe Valley',
    'North Beach',
    'Pacific Heights',
    'Potrero Hill',
    'Russian Hill',
    'SoMa',
  ],
  'San Jose': [
    'Almaden Valley',
    'Berryessa',
    'Cambrian',
    'Campbell',
    'Downtown',
    'East San Jose',
    'Evergreen',
    'Japantown',
    'Rose Garden',
    'West San Jose',
    'Willow Glen',
  ],
  'Seattle': [
    'Ballard',
    'Beacon Hill',
    'Capitol Hill',
    'Central District',
    'Columbia City',
    'Downtown',
    'Fremont',
    'Georgetown',
    'Green Lake',
    'International District',
    'Queen Anne',
    'South Lake Union',
    'University District',
    'Wallingford',
    'West Seattle',
  ],
  'St. Louis': [
    'Benton Park',
    'Central West End',
    'Cherokee Street',
    'Clayton',
    'Dogtown',
    'Downtown',
    'Lafayette Square',
    'Maplewood',
    'Shaw',
    'Soulard',
    'The Grove',
    'The Hill',
    'Tower Grove',
  ],
  'Tampa': [
    'Bayshore',
    'Channel District',
    'Davis Islands',
    'Downtown',
    'Hyde Park',
    'New Tampa',
    'Palma Ceia',
    'Seminole Heights',
    'SoHo',
    'Westchase',
    'Ybor City',
  ],
  'Washington': [
    'Adams Morgan',
    'Capitol Hill',
    'Columbia Heights',
    'Dupont Circle',
    'Foggy Bottom',
    'Georgetown',
    'H Street',
    'Logan Circle',
    'Navy Yard',
    'NoMa',
    'Penn Quarter',
    'Petworth',
    'Shaw',
    'U Street',
  ],
};
