export const US_CITIES: string[] = [
  "Abilene, TX",
  "Akron, OH",
  "Albany, GA",
  "Albany, NY",
  "Albuquerque, NM",
  "Alexandria, LA",
  "Alexandria, VA",
  "Allen, TX",
  "Allentown, PA",
  "Amarillo, TX",
  "Anaheim, CA",
  "Anchorage, AK",
  "Ann Arbor, MI",
  "Antioch, CA",
  "Apple Valley, CA",
  "Arlington, TX",
  "Arlington, VA",
  "Arvada, CO",
  "Asheville, NC",
  "Athens, GA",
  "Atlanta, GA",
  "Augusta, GA",
  "Aurora, CO",
  "Aurora, IL",
  "Austin, TX",
  "Bakersfield, CA",
  "Baltimore, MD",
  "Bangor, ME",
  "Baton Rouge, LA",
  "Beaumont, TX",
  "Bellevue, WA",
  "Berkeley, CA",
  "Bethlehem, PA",
  "Billings, MT",
  "Biloxi, MS",
  "Birmingham, AL",
  "Bismarck, ND",
  "Bloomington, IL",
  "Bloomington, IN",
  "Boca Raton, FL",
  "Boise, ID",
  "Boston, MA",
  "Boulder, CO",
  "Bowling Green, KY",
  "Bozeman, MT",
  "Bridgeport, CT",
  "Broken Arrow, OK",
  "Brownsville, TX",
  "Bryan, TX",
  "Buffalo, NY",
  "Burbank, CA",
  "Burlington, VT",
  "Cambridge, MA",
  "Cape Coral, FL",
  "Carlsbad, CA",
  "Carrollton, TX",
  "Carson City, NV",
  "Cary, NC",
  "Casper, WY",
  "Cedar Rapids, IA",
  "Centennial, CO",
  "Chandler, AZ",
  "Charleston, SC",
  "Charleston, WV",
  "Charlotte, NC",
  "Charlottesville, VA",
  "Chattanooga, TN",
  "Chesapeake, VA",
  "Cheyenne, WY",
  "Chicago, IL",
  "Chula Vista, CA",
  "Cincinnati, OH",
  "Clarksville, TN",
  "Clearwater, FL",
  "Cleveland, OH",
  "College Station, TX",
  "Colorado Springs, CO",
  "Columbia, MO",
  "Columbia, SC",
  "Columbus, GA",
  "Columbus, OH",
  "Concord, CA",
  "Concord, NC",
  "Coral Springs, FL",
  "Corona, CA",
  "Corpus Christi, TX",
  "Costa Mesa, CA",
  "Cranston, RI",
  "Dallas-Fort Worth, TX",
  "Dallas, TX",
  "Daly City, CA",
  "Davenport, IA",
  "Davie, FL",
  "Dayton, OH",
  "Daytona Beach, FL",
  "Dearborn, MI",
  "Decatur, IL",
  "Deltona, FL",
  "Denton, TX",
  "Denver, CO",
  "Des Moines, IA",
  "Detroit, MI",
  "Downey, CA",
  "Duluth, MN",
  "Durham, NC",
  "East Los Angeles, CA",
  "Edison, NJ",
  "Edmond, OK",
  "El Cajon, CA",
  "El Monte, CA",
  "El Paso, TX",
  "Elgin, IL",
  "Elizabeth, NJ",
  "Elk Grove, CA",
  "Erie, PA",
  "Escondido, CA",
  "Eugene, OR",
  "Evansville, IN",
  "Everett, WA",
  "Fairbanks, AK",
  "Fairfax, VA",
  "Fall River, MA",
  "Fargo, ND",
  "Fayetteville, AR",
  "Fayetteville, NC",
  "Flagstaff, AZ",
  "Flint, MI",
  "Fontana, CA",
  "Fort Collins, CO",
  "Fort Lauderdale, FL",
  "Fort Myers, FL",
  "Fort Smith, AR",
  "Fort Wayne, IN",
  "Fort Worth, TX",
  "Frederick, MD",
  "Fremont, CA",
  "Fresno, CA",
  "Frisco, TX",
  "Fullerton, CA",
  "Gainesville, FL",
  "Garden Grove, CA",
  "Garland, TX",
  "Gary, IN",
  "Gilbert, AZ",
  "Glendale, AZ",
  "Glendale, CA",
  "Grand Forks, ND",
  "Grand Junction, CO",
  "Grand Prairie, TX",
  "Grand Rapids, MI",
  "Great Falls, MT",
  "Greeley, CO",
  "Green Bay, WI",
  "Greensboro, NC",
  "Greenville, SC",
  "Gresham, OR",
  "Gulfport, MS",
  "Hampton, VA",
  "Harrisburg, PA",
  "Hartford, CT",
  "Hattiesburg, MS",
  "Hayward, CA",
  "Henderson, NV",
  "Hialeah, FL",
  "High Point, NC",
  "Hillsboro, OR",
  "Hollywood, FL",
  "Honolulu, HI",
  "Houston, TX",
  "Huntington Beach, CA",
  "Huntington, WV",
  "Huntsville, AL",
  "Idaho Falls, ID",
  "Independence, MO",
  "Indianapolis, IN",
  "Inglewood, CA",
  "Irvine, CA",
  "Irving, TX",
  "Jackson, MS",
  "Jackson, WY",
  "Jacksonville, FL",
  "Jacksonville, NC",
  "Jersey City, NJ",
  "Johnson City, TN",
  "Joliet, IL",
  "Juneau, AK",
  "Kailua, HI",
  "Kalamazoo, MI",
  "Kansas City, KS",
  "Kansas City, MO",
  "Kenner, LA",
  "Kent, WA",
  "Killeen, TX",
  "Knoxville, TN",
  "Lafayette, LA",
  "Lake Charles, LA",
  "Lakeland, FL",
  "Lakewood, CO",
  "Lancaster, CA",
  "Lancaster, PA",
  "Lansing, MI",
  "Laredo, TX",
  "Las Cruces, NM",
  "Las Vegas, NV",
  "Lawrence, KS",
  "Lawton, OK",
  "Lewisville, TX",
  "Lexington, KY",
  "Lincoln, NE",
  "Little Rock, AR",
  "Long Beach, CA",
  "Los Angeles, CA",
  "Louisville, KY",
  "Lowell, MA",
  "Lubbock, TX",
  "Lynchburg, VA",
  "Lynn, MA",
  "Macon, GA",
  "Madison, WI",
  "Manchester, NH",
  "McAllen, TX",
  "McKinney, TX",
  "Melbourne, FL",
  "Memphis, TN",
  "Merced, CA",
  "Mesa, AZ",
  "Mesquite, TX",
  "Miami Gardens, FL",
  "Miami, FL",
  "Midland, TX",
  "Milwaukee, WI",
  "Minneapolis-St. Paul, MN",
  "Minneapolis, MN",
  "Miramar, FL",
  "Missoula, MT",
  "Mobile, AL",
  "Modesto, CA",
  "Monroe, LA",
  "Montgomery, AL",
  "Moreno Valley, CA",
  "Murfreesboro, TN",
  "Murrieta, CA",
  "Myrtle Beach, SC",
  "Nampa, ID",
  "Naperville, IL",
  "Nashua, NH",
  "Nashville, TN",
  "New Bedford, MA",
  "New Haven, CT",
  "New Orleans, LA",
  "New York, NY",
  "Newark, DE",
  "Newark, NJ",
  "Newport News, VA",
  "Norfolk, VA",
  "Norman, OK",
  "North Charleston, SC",
  "North Las Vegas, NV",
  "Norwalk, CA",
  "Norwalk, CT",
  "Oakland, CA",
  "Ocala, FL",
  "Oceanside, CA",
  "Odessa, TX",
  "Ogden, UT",
  "Oklahoma City, OK",
  "Olathe, KS",
  "Olympia, WA",
  "Omaha, NE",
  "Ontario, CA",
  "Orange, CA",
  "Orlando, FL",
  "Overland Park, KS",
  "Oxnard, CA",
  "Palm Bay, FL",
  "Palm Springs, CA",
  "Palmdale, CA",
  "Panama City, FL",
  "Pasadena, CA",
  "Pasadena, TX",
  "Paterson, NJ",
  "Pearland, TX",
  "Pembroke Pines, FL",
  "Pensacola, FL",
  "Peoria, AZ",
  "Peoria, IL",
  "Philadelphia, PA",
  "Phoenix, AZ",
  "Pittsburgh, PA",
  "Plano, TX",
  "Pocatello, ID",
  "Pomona, CA",
  "Pompano Beach, FL",
  "Port St. Lucie, FL",
  "Portland, ME",
  "Portland, OR",
  "Portsmouth, VA",
  "Providence, RI",
  "Provo, UT",
  "Pueblo, CO",
  "Raleigh, NC",
  "Rancho Cucamonga, CA",
  "Rapid City, SD",
  "Reading, PA",
  "Reno, NV",
  "Rialto, CA",
  "Richardson, TX",
  "Richmond, CA",
  "Richmond, VA",
  "Riverside, CA",
  "Roanoke, VA",
  "Rochester, MN",
  "Rochester, NY",
  "Rockford, IL",
  "Roseville, CA",
  "Round Rock, TX",
  "Sacramento, CA",
  "Saginaw, MI",
  "Salem, OR",
  "Salt Lake City, UT",
  "San Angelo, TX",
  "San Antonio, TX",
  "San Bernardino, CA",
  "San Diego, CA",
  "San Francisco Bay Area, CA",
  "San Francisco, CA",
  "San Jose, CA",
  "San Marcos, TX",
  "San Mateo, CA",
  "Sandy Springs, GA",
  "Santa Ana, CA",
  "Santa Barbara, CA",
  "Santa Clara, CA",
  "Santa Clarita, CA",
  "Santa Cruz, CA",
  "Santa Fe, NM",
  "Santa Maria, CA",
  "Santa Rosa, CA",
  "Sarasota, FL",
  "Savannah, GA",
  "Scottsdale, AZ",
  "Scranton, PA",
  "Seattle, WA",
  "Shreveport, LA",
  "Simi Valley, CA",
  "Sioux City, IA",
  "Sioux Falls, SD",
  "South Bend, IN",
  "Sparks, NV",
  "Spokane, WA",
  "Springfield, IL",
  "Springfield, MA",
  "Springfield, MO",
  "St. Cloud, MN",
  "St. George, UT",
  "St. Louis, MO",
  "St. Paul, MN",
  "St. Petersburg, FL",
  "Stamford, CT",
  "Sterling Heights, MI",
  "Stockton, CA",
  "Sugar Land, TX",
  "Sunnyvale, CA",
  "Surprise, AZ",
  "Syracuse, NY",
  "Tacoma, WA",
  "Tallahassee, FL",
  "Tampa, FL",
  "Temecula, CA",
  "Tempe, AZ",
  "Terre Haute, IN",
  "Thornton, CO",
  "Thousand Oaks, CA",
  "Toledo, OH",
  "Topeka, KS",
  "Torrance, CA",
  "Trenton, NJ",
  "Tucson, AZ",
  "Tulsa, OK",
  "Tuscaloosa, AL",
  "Tyler, TX",
  "Utica, NY",
  "Vallejo, CA",
  "Vancouver, WA",
  "Victorville, CA",
  "Virginia Beach, VA",
  "Visalia, CA",
  "Waco, TX",
  "Warren, MI",
  "Warwick, RI",
  "Washington, DC",
  "Waterbury, CT",
  "Waterloo, IA",
  "West Covina, CA",
  "West Jordan, UT",
  "West Palm Beach, FL",
  "West Valley City, UT",
  "Westminster, CO",
  "Wichita Falls, TX",
  "Wichita, KS",
  "Wilmington, DE",
  "Wilmington, NC",
  "Winston-Salem, NC",
  "Woodbridge, NJ",
  "Worcester, MA",
  "Yakima, WA",
  "Yonkers, NY",
  "Youngstown, OH",
  "Yuma, AZ",
];
